### ISSUE TITLE
Clean code, optimize and bugfixes

### ISSUE THREAD

**Issue by LordRibblesdale** [MyLibreLab/MyLibreLab#30]
Hi! I've forked this repository to manage some (imho) problems and bugs.
[Here there is my changes](https://github.com/MyLibreLab/MyLibreLab/compare/master...LordRibblesdale:master). Main changes are:
- Some "for" changed into "for each", for code readability
- Strings to StringBuilder (quicker access to strings, especially for longer ones)
- Fix for "new Comparator()" used in some ArrayList sorting
- Refactors to some methods, [like this one](https://github.com/LordRibblesdale/MyLibreLab/blob/master/src/main/java/VisualLogic/Basis.java#L1940), also for code readability

I'd like to hear some opinions before creating a first pull request.
Thanks in advance!

**Comment by marko-radosavljevic** [comment]
Sure! But do not do any work until we merge #26. (should be done soon)

**Comment by marko-radosavljevic** [comment]
Closed because issue scope is too large, please open issues for more specific problems, so we can have clean git history and cleaner GitHub documentation ^^

"Clean code, optimize and bugfixes" includes every single line of code, its very uninformative what the issue is about, and fixes would touch every part of the codebase, so grepping through git history would be a nightmare.

Not your fault, we still don't have CONTRIBUTING.md with clear guidelines. So yeah, open much more contained issues for every thing you see that is wrong. ^^
