### ISSUE TITLE
Implement api for application events.

### ISSUE THREAD

**Issue by weisJ** [MyLibreLab/MyLibreLab#67]
Currently actions in the application are very tightly coupled to the ui implementation. We should implement an event bus like api to handle messaging between components (in the ui and abstract sense) of the application.

Capabilities:
- Components should be able to subscribe to certain event types.
- Components should be able to send events to certain event types.
- Events are strongly typed both for senders and receivers.
- Posting a notification should not deadlock the ui. Though Consumers of events are responsible for not blocking
  the event bus. (Maybe provide some api for background tasks that wraps the `SwingWorker` api).
- Utility methods for binding to ui components e.g. buttons, menus etc.

Example situation:
We have an "action" button which when pressed causes something to happen.
````java
// postNotification should only take events of type ButtonPressedEvent.
button.addActionListener(e -> EventBus.get(ACTION_BUTTON_PRESSED).postNotification(new ButtonPressedEvent(...));


// when #subscribe should take Consumer<ButtonPressedEvent>
// Somewhere else
EventBus.get(ACTION_BUTTON_PRESSED).subscribe(actionConsumer1, e -> doSomethingWithButtonPressedEvent(e));
// Again somewhere else
EventBus.get(ACTION_BUTTON_PRESSED).subscribe(actionConsumer2, e -> doSomethingElseWithButtonPressedEvent(e));
````

**Comment by marko-radosavljevic** [comment]
Yup! :100:

**Comment by marko-radosavljevic** [comment]
To expand on this,

I think this is a good design decision at our current state of the rewrite. Because we can just cut out the legacy module, and replace it with the new one. We have API in front, and a very loose coupling because only objects are shared between modules. Basically simple facade and mediator like design.

Loose coupling and modular design will give us flexibility we need to make big changes while still moving at a decent pace.
